"""Fill the LangAI 3.0 AI-disclosure template -> submission/LangAI3.0_AI_Disclosure.docx.

Team details come from submission/team.json. Signature, representative name, role and dates are
left blank on purpose: only a team member can sign the declaration.
"""
from __future__ import annotations

import copy
import json
from pathlib import Path

from docx import Document
from docx.shared import Pt

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = ROOT / "submission" / "templates" / "LangAI3.0_AI_Disclosure_template.docx"
OUT = ROOT / "submission" / "LangAI3.0_AI_Disclosure.docx"
TEAM = json.loads((ROOT / "submission" / "team.json").read_text())

AI_TOOL = ("Claude Code (Anthropic's AI coding agent, model Claude Opus 5.5), run on the team's laptop; "
           "sub-agents of the same tool were used for corpus and benchmark authoring")

PURPOSES = {
    "Idea generation": "Yes - the architecture (speculative per-clause retrieval, turn gate, versioned answers, "
                       "entity x aspect uncertainty) was proposed by the AI assistant from the Theme 4 guide and adopted "
                       "by the team.",
    "Code generation": "Yes - most of the Python engine, benchmark harness, CLI, server and scripts were written by the "
                       "AI coding agent and iteratively tested/refined against our dev benchmark.",
    "UI / UX design": "Yes - the web demo UI (HTML/CSS/JS) was generated by the AI agent and checked in Chromium.",
    "Content creation": "Yes - the synthetic 46-document corpus (fictional company, from an AI-drafted spec), benchmark "
                        "utterances, README/docs, presentation text and the demo-video storyboard were drafted with AI.",
    "Data analysis": "Yes - benchmark error analysis, threshold calibration on the dev split and figure generation.",
    "Testing / debugging": "Yes - unit/end-to-end tests, smoke test and debugging were done with the AI agent.",
    "Other": "Runtime: the prototype itself uses only two small open-source ONNX models (BAAI/bge-small-en-v1.5, "
             "ms-marco-MiniLM-L-6-v2); no generative model in the default answer path. Demo video recorded "
             "automatically (Playwright): animated storyboard scenes plus guided-tour recordings of live replays, no narration.",
}

FEATURES = [
    ("Streaming retrieval controller (turn gate + stability gate, speculative retrieval)", "AI-Generated (team-directed, reviewed)",
     "Tool: Claude Code. Prompt: build a Theme 4 streaming live RAG system from the guide (retrieve before the utterance ends, "
     "decide when retrieval is needed). Output: rule / model / hybrid turn gate, clause stability gate, entity-aware reuse of "
     "speculative results. Modification: tuned from dev-set error analysis (false triggers, refinement cues)."),
    ("Multi-intent decomposition of spoken utterances", "AI-Generated (team-directed, reviewed)",
     "Tool: Claude Code. Output: filler/self-repair/spoken-number normalisation, clause labelling, context carry-over, anaphora "
     "handling, fragment merging. Modification: generalisation fixes after the first held-out run (unknown words, repairs)."),
    ("Hybrid retrieval, RRF fusion and cross-encoder reranking", "AI-Generated (team-directed, reviewed)",
     "Tool: Claude Code, using open-source models BAAI/bge-small-en-v1.5 and ms-marco-MiniLM-L-6-v2 via fastembed/ONNX. "
     "Output: BM25 + dense retrieval, RRF, reranking, context-hedged queries. Modification: CPU latency budget tuning."),
    ("Session-aware grounded synthesis, versioning and uncertainty flags", "AI-Generated (team-directed, reviewed)",
     "Tool: Claude Code. Output: extractive cited claims, grounding verifier, versioned answers with delta refinement, "
     "presentation transforms, typed-quantity / entity-attribute / sibling-coverage uncertainty. Optional LLM mode is verified."),
    ("Telemetry, benchmark harness, baseline and ablations", "AI-Generated (team-directed, reviewed)",
     "Tool: Claude Code. Output: JSONL telemetry + schema, discrete-event replay, gate metrics G1-G6, baseline and 7 ablations."),
    ("Real-time web demo (FastAPI/WebSocket UI, mic input)", "AI-Generated (team-directed, reviewed)",
     "Tool: Claude Code. Output: three-panel live UI, scenario replay, Web Speech API microphone input, trace download."),
    ("Synthetic corpus and benchmark datasets", "AI-Generated",
     "Tool: Claude Code sub-agents. Prompt: write 46 fictional policy/venue/IT documents from a per-document fact sheet; write dev and "
     "held-out streaming sessions with gold labels without reading the code. Output validated by scripts; all content fictional."),
    ("Documentation, presentation and demo video", "AI-Generated (team to review before submission)",
     "Tool: Claude Code (python-pptx on the official template, matplotlib figures, HTML/CSS motion graphics, Playwright recording). "
     "Output: README, architecture brief, benchmark report, deck, video."),
]


def set_after_label(p, text: str) -> None:
    """Keep the label run(s), replace the trailing underscore placeholder with the answer."""
    runs = p.runs
    blank = next((r for r in reversed(runs) if set(r.text.strip()) <= {"_"} and r.text.strip()), None)
    if blank is None:
        p.add_run(" " + text)
        return
    blank.text = " " + text


def main() -> None:
    doc = Document(TEMPLATE)
    P = doc.paragraphs
    set_after_label(P[3], TEAM["team_name"])
    set_after_label(P[4], TEAM["project_name"])
    set_after_label(P[5], TEAM["college"])
    set_after_label(P[6], TEAM.get("submission_date") or "____________ (to be filled by the team)")
    # 2. AI usage declaration: mark "Yes"
    for r in P[9].runs:
        if r.text.strip() == "Yes / No":
            r.text = "Yes"
            r.bold = True
    P[10].runs[0].text = ("An AI coding agent was used extensively to design, implement, test and document this "
                          f"project. Tool: {AI_TOOL}.")
    # 3. purposes
    keys = ["Idea generation", "Code generation", "UI / UX design", "Content creation", "Data analysis",
            "Testing / debugging", "Other"]
    for idx, key in zip(range(13, 20), keys):
        p = P[idx]
        # template runs: label run(s) + underscore run(s)
        for r in p.runs:
            if set(r.text.strip()) <= {"_"}:
                r.text = ""
        p.add_run(" - " + PURPOSES[key])
    # 4. feature blocks: the template has two blocks (22-24, 26-28) and an ellipsis (29)
    block = [P[22]._p, P[23]._p, P[24]._p, P[25]._p]
    anchor = P[29]._p
    # remove the template blocks and the ellipsis, then insert one block per feature before the anchor
    body = anchor.getparent()
    for el in [P[22]._p, P[23]._p, P[24]._p, P[25]._p, P[26]._p, P[27]._p, P[28]._p]:
        body.remove(el)
    for k, (name, origin, desc) in enumerate(FEATURES, 1):
        els = [copy.deepcopy(b) for b in block]
        for el in els:
            anchor.addprevious(el)
    body.remove(anchor)
    doc2 = doc  # paragraphs list refresh
    paras = doc2.paragraphs
    start = next(i for i, p in enumerate(paras) if p.text.startswith("4. "))
    i = start + 1
    for k, (name, origin, desc) in enumerate(FEATURES, 1):
        pn, po, pd = paras[i], paras[i + 1], paras[i + 2]
        for p in (pn, po, pd):
            for r in p.runs[1:]:
                r.text = ""
        pn.runs[0].text = f"Feature {k}. Feature Name: {name}"
        pn.runs[0].bold = True
        po.runs[0].text = f"Self-Generated/AI-Generated/Both: {origin}"
        pd.runs[0].text = f"Description: {desc}"
        for p in (pn, po, pd):
            for r in p.runs:
                r.font.size = Pt(10.5)
        i += 4
    # 5. compliance: keep "Yes" / "I Agree"; add a short provenance note
    comp = next(p for p in doc.paragraphs if p.text.startswith("No proprietary or copyrighted data misused"))
    note = comp.insert_paragraph_before("")
    comp._p.addnext(copy.deepcopy(note._p))
    note._p.getparent().remove(note._p)
    after = next(p for p in doc.paragraphs if p.text == "" and p._p.getprevious() is comp._p)
    after.add_run("All corpus content is fictional (authored for this project); models are open-source "
                  "(bge-small-en-v1.5: MIT, ms-marco-MiniLM-L-6-v2: Apache-2.0). No personal or proprietary data was used.")
    after.runs[0].font.size = Pt(10)
    # 6. sign-off: left for the team representative
    for label in ("Name of Team Representative:", "Role:", "Signature:", "Date:"):
        p = next(p for p in doc.paragraphs if p.text.strip() == label)
        p.add_run(" ______________________________")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    doc.save(OUT)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
